<h3>Basics</h3>

In [ ]:
import numpy as np

In [17]:
a = np.array([1,2,3],dtype = "int32")
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# get dimension
a.ndim

1

In [10]:
# get shape
b.shape

(2, 3)

In [14]:
#get type
a.dtype

dtype('int16')

In [19]:
# GET SIZE
a.itemsize
# one byte = 8 bits so 16 = 2 size and 32 = 4 size

4

In [25]:
# get total size 
a.size * a.itemsize
# both are the same thing
a.nbytes

12

<h3>Accesssing/ Chnaging specific elements, rows, columns, etc</h3>

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# get a specific element [r,c]
print(a[1,5])

13


In [29]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [36]:
#Getting a lil more fancy [startindex:endindex:stepsize]
a[0,1:-2:2]
a[0,1:6:2]
a[0,1:-2:2]

array([2, 4])

In [38]:
a[1:5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [20 20 20 20 20 20 20]]
[[ 1  2  1  4  5  6  7]
 [20 20  2 20 20 20 20]]


<h3>*3-d example</h3>

In [43]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
# Get Specific element (Work outside in )
b[0,1,1]
b[:,0,0]
b[:,:,:]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [47]:
# replace 

In [49]:
b [:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


<h3>Initializing differnet types of Arrays</h3>

In [50]:
# All zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
# All is matrix
np.ones((4,2,2), dtype= "int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [54]:
# any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [55]:
#any other number
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [61]:
# random decimal numbers
np.random.random_sample(a.shape)

array([[0.50687643, 0.23009388, 0.99717557, 0.09732048, 0.67954238,
        0.25502828, 0.96558809],
       [0.61254219, 0.90318131, 0.69287732, 0.07535448, 0.59531151,
        0.20711794, 0.19430129]])

In [65]:
output = np.ones(( 5,5 ))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output [1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#####Be careful when copying arrays